displayName: Device info from User Agent

summary: "Parses User-Agent header to retrieve device information and pass it upstream via HTTP Headers."

type: middleware

import: github.com/GiGInnovationLabs/traefikuseragent

testData: {}
